### ISSUE TITLE
Add command to send a "command message"

### ISSUE THREAD

**Issue by ctron** [drogue-iot/drg#10]
Currently we use the following command to publish a command message for a device:

~~~
http POST $COMMAND_ENDPOINT_URL/command?application=app_id\&device=device_id\&command=set-temp temp:=25" \"Authorization:Bearer \$TOKEN\"
~~~

However, this includes the access token, and it would be easier if the `drg` tool would have out of the box support for this. Something like:

~~~
drg send-command <appid> <deviceid> <command> <payload>
~~~

With the option to consume payload from `stdin`:

~~~
echo "foo bar" | drg send-command <appid> <deviceid> <command>
~~~

Note: syntax of the command is just an example

**Comment by vedangj044** [comment]
I would like to work on this one.
Please confirm that we have to add `comman_url` to the endpoints list so that we fetch them at the time of login and save them in the config of drg.

**Comment by jcrossley3** [comment]
I like this idea. It would obviate drogue-cloud's `./scripts/publish.sh`, which I use a lot.

I would only suggest a different, more concise subcommand name, e.g. `emit`, `send`, `publish`, etc.
