### ISSUE TITLE
Consider renaming --data to --spec

### ISSUE THREAD

**Issue by ctron** [drogue-iot/drg#12]
I just ran into the issue that I provided a full data section to the --data argument … however, that seems to already encapsulate it into the `spec` section. Which is fine, but then the `--data` argument feels a bit misleading.

My recommendation would be to rename the argument to `--spec`.

**Comment by rishabh-vasudevan** [comment]
I have renamed the --data command to --spec. This was the first time I have coded in Rust so if you see an error I have made please let me know I will try to fix it.
Pull request #26
