### ISSUE TITLE
Allow using custom trust anchor with `drg stream`

### ISSUE THREAD

**Issue by ctron** [drogue-iot/drg#143]
Currently `drg stream` with `wss://` (TLS) requires a valid system trust anchor.

It should be possible to:

* [ ] Provide a custom trust anchor (e.g. `--ca-cert <file>`)
* [x] Allow disabling TLS validation (`--insecure`)

**Comment by jbtrystram** [comment]
closing this, as it's a duplicate of https://github.com/drogue-iot/drg/issues/29
