### ISSUE TITLE
GLIBC version error on Debian

### ISSUE THREAD

**Issue by vedangj044** [drogue-iot/drg#43]
Trying to run binaries from the release page on Debian output the following error.
```
./drg-linux-amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./drg-linux-amd64)
```

**Comment by ctron** [comment]
Compiling this with CentOS 8, RHEL 8, Ubuntu <no-sure-which-version> should solve this issue. Fedora is just too new.

**Comment by vedangj044** [comment]
Sure working on this
