### ISSUE TITLE
Have errors return a non-zero status

### ISSUE THREAD

**Issue by jcrossley3** [drogue-iot/drg#8]
Scripting `drg` would be facilitated by returning a non-zero status for all errors -- not just malformed arguments. This would enable a shell script to simply check $? instead of having to parse stdout for "Error..." for say, an invalid app id. Basically, anything that might println in [this code](https://github.com/drogue-iot/drg/blob/28510df476664341ad8a13d269c325d5dad3e60f/src/util.rs#L20-L39) should result in a non-zero exit status to the shell.

It's fine to print the output, of course. Just don't return 0 to the shell when you do.

**Comment by jbtrystram** [comment]
Errors codes proposal 

- User syntax error (invalid JSON input or invalid URLs for example) : return `1`
- User error on the resource (404, 409 ..) : return `2`
- Network errors : return `3`
- Authentication problems : return `4`

**Comment by lulf** [comment]
@jbtrystram One option would be to follow common used error codes for unix utilities, such as:

```
#define	EPERM		 1	/* Operation not permitted */
#define	ENOENT		 2	/* No such file or directory */
#define	ESRCH		 3	/* No such process */
#define	EINTR		 4	/* Interrupted system call */
#define	EIO		 5	/* I/O error */
#define	ENXIO		 6	/* No such device or address */
#define	E2BIG		 7	/* Argument list too long */
#define	ENOEXEC		 8	/* Exec format error */
#define	EBADF		 9	/* Bad file number */
#define	ECHILD		10	/* No child processes */
#define	EAGAIN		11	/* Try again */
#define	ENOMEM		12	/* Out of memory */
#define	EACCES		13	/* Permission denied */
#define	EFAULT		14	/* Bad address */
#define	ENOTBLK		15	/* Block device required */
#define	EBUSY		16	/* Device or resource busy */
#define	EEXIST		17	/* File exists */
#define	EXDEV		18	/* Cross-device link */
#define	ENODEV		19	/* No such device */
#define	ENOTDIR		20	/* Not a directory */
#define	EISDIR		21	/* Is a directory */
#define	EINVAL		22	/* Invalid argument */
#define	ENFILE		23	/* File table overflow */
#define	EMFILE		24	/* Too many open files */
#define	ENOTTY		25	/* Not a typewriter */
#define	ETXTBSY		26	/* Text file busy */
#define	EFBIG		27	/* File too large */
#define	ENOSPC		28	/* No space left on device */
#define	ESPIPE		29	/* Illegal seek */
#define	EROFS		30	/* Read-only file system */
#define	EMLINK		31	/* Too many links */
#define	EPIPE		32	/* Broken pipe */
#define	EDOM		33	/* Math argument out of domain of func */
#define	ERANGE		34	/* Math result not representable */
```

So, auth issues would be `1` or `13`, network issues would be `5`, 40x would be `2`, etc.  The errno numbers are a bit old ("Not a typewriter" :P), so it's not always a good fit, but they make up for it by being easy to google search for.

No matter what numbers used, error codes should be well documented to what they mean for that particular tool.

**Comment by jbtrystram** [comment]
@lulf in any case there must be documentation somewhere about the error codes `drg` will use. but you are right, the more standard the better. I did not know there was a standard for error codes. TIL :)

**Comment by ctron** [comment]
In any case, regarding error reporting:

* If something went wrong, exit with an error value >0
* Errors should be printed to "stderr", rather than "stdout"

**Comment by vedangj044** [comment]
I would like to work on this.
